package com.gateflow.sdk;

import com.gateflow.sdk.model.TrackEvent;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.Arrays;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class GateFlowClientTest {

    @Test
    void buildMinimalEvent() {
        TrackEvent event = TrackEvent.builder("page_view")
                .userId("user_123")
                .build();

        assertNotNull(event.getEventId());
        assertEquals("page_view", event.getEventType());
        assertEquals("user_123", event.getUserId());
        assertEquals("server", event.getPlatform());
        assertNotNull(event.getTimestamp());
    }

    @Test
    void buildFullEvent() {
        Instant ts = Instant.parse("2026-06-08T10:00:00Z");
        TrackEvent event = TrackEvent.builder("purchase")
                .eventId("evt_custom_001")
                .userId("user_456")
                .anonymousId("anon_789")
                .sessionId("sess_abc")
                .timestamp(ts)
                .spma("myapp").spmb("b_checkout").spmc("order").spmd("confirm")
                .pageUrl("https://shop.example.com/checkout")
                .pageTitle("Checkout")
                .platform("android")
                .deviceType("mobile").os("Android").browser("Chrome")
                .screenWidth(1080).screenHeight(2400).language("zh-CN")
                .elementId("btn_pay").elementType("button").elementText("Pay Now")
                .utmSource("wechat").utmMedium("social").utmCampaign("double11")
                .property("orderId", "ORD-9982")
                .property("amount", 299.00)
                .property("currency", "CNY")
                .build();

        assertEquals("evt_custom_001", event.getEventId());
        assertEquals("purchase", event.getEventType());
        assertEquals("user_456", event.getUserId());
        assertEquals("anon_789", event.getAnonymousId());
        assertEquals("sess_abc", event.getSessionId());
        assertEquals(ts, event.getTimestamp());
        assertEquals("myapp", event.getSpma());
        assertEquals("b_checkout", event.getSpmb());
        assertEquals("order", event.getSpmc());
        assertEquals("confirm", event.getSpmd());
        assertEquals("https://shop.example.com/checkout", event.getPageUrl());
        assertEquals("android", event.getPlatform());
        assertEquals("mobile", event.getDeviceType());
        assertEquals("Android", event.getOs());
        assertEquals("wechat", event.getUtmSource());
        assertEquals("double11", event.getUtmCampaign());

        Map<String, Object> props = event.getProperties();
        assertEquals("ORD-9982", props.get("orderId"));
        assertEquals(299.00, props.get("amount"));
    }

    @Test
    void eventTypeRequired() {
        assertThrows(IllegalArgumentException.class, () -> TrackEvent.builder(null).build());
        assertThrows(IllegalArgumentException.class, () -> TrackEvent.builder("  ").build());
    }

    @Test
    void autoGeneratedEventId() {
        TrackEvent e1 = TrackEvent.builder("click").build();
        TrackEvent e2 = TrackEvent.builder("click").build();
        assertNotNull(e1.getEventId());
        assertNotEquals(e1.getEventId(), e2.getEventId());
    }

    @Test
    void builderCreatesClient() {
        // Just verify construction works (doesn't try to connect)
        GateFlowClient client = GateFlowClient.builderLocalhost()
                .clientId("test-svc")
                .batchSize(10)
                .flushIntervalSec(60)
                .maxRetries(1)
                .queueCapacity(100)
                .build();

        assertEquals(0, client.queueSize());

        boolean ok = client.track(TrackEvent.builder("test_event")
                .userId("test_user")
                .build());
        assertTrue(ok);
        assertEquals(1, client.queueSize());

        client.shutdown();
    }

    @Test
    void identifyEnqueuesIdentifyEvent() {
        GateFlowClient client = GateFlowClient.builderLocalhost().flushIntervalSec(60).build();

        assertTrue(client.identify("anon_1", "user_1"));
        assertEquals(1, client.queueSize());

        // 缺失任一 id 不入队
        assertFalse(client.identify("anon_1", ""));
        assertFalse(client.identify(null, "user_1"));
        assertEquals(1, client.queueSize());

        client.shutdown();
    }

    @Test
    void trackAll() {
        GateFlowClient client = GateFlowClient.builderLocalhost()
                .flushIntervalSec(60)
                .build();

        int count = client.trackAll(Arrays.asList(
                TrackEvent.builder("e1").userId("u1").build(),
                TrackEvent.builder("e2").userId("u1").build(),
                TrackEvent.builder("e3").userId("u1").build()
        ));
        assertEquals(3, count);
        assertEquals(3, client.queueSize());

        client.shutdown();
    }
}
